---
- name: start mysql
  k8s:
    definition:
      kind: StatefulSet
      apiVersion: apps/v1
      metadata:
        name: 'mysql-deployment'
        namespace: '{{ meta.namespace }}'
      spec:
        replicas: "{{size}}"
        selector:
          matchLabels:
            app: mysql
        template:
          metadata:
            labels:
              app: mysql
          spec:
            containers:
            - name: mysql
              image: "{{image}}"
              ports:
              - containerPort: 3306
              envFrom: 
               - configMapRef: 
                  name: mysql-cm 
              env:
              - name: WATCH_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: OPERATOR_NAME
                value: "example-mysql-mysql"
              volumeMounts:
              - name: mysql-data
                mountPath: "/mnt/data"
            volumes:
            - name: mysql-data
              persistentVolumeClaim:
                claimName: mysql-pvc-vol1

- name: Create the  service
  k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: service
        namespace: '{{ meta.namespace }}'
        labels:
          app: mysql
      spec:
        ports:
        - name: database
          port: 3306
          protocol: TCP
          targetPort: 3306
        selector:
          app: mysql
